"""change required created updated

Revision ID: 6e7f8599a80c
Revises: 61f0ad82b2dd
Create Date: 2025-01-13 11:01:12.759151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e7f8599a80c'
down_revision: Union[str, None] = '61f0ad82b2dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contents', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('contents', 'updated_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'updated_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('contents', 'updated_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('contents', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
